model {
  file: "model.sdf"
}
name: "MODERN_DOLL_FAMILY"
description: "MODERN DOLL FAMILY\nFashionably clothed dolls scaled to fit PlanDollhouse."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "7142"
}
annotations {
  key: "sku"
  value: "0714200"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
